package com.mulesoft.demo.sumtotal.client.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-20T11:10:37.483-07:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", name = "AuthenticationSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthenticationSoap {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetLoggedInUserResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", partName = "parameters")
    @WebMethod(operationName = "GetLoggedInUser", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/GetLoggedInUser")
    public GetLoggedInUserResponse getLoggedInUser(
        @WebParam(partName = "parameters", name = "GetLoggedInUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        GetLoggedInUser parameters
    );

    @RequestWrapper(localName = "SetWorkingDomain", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.SetWorkingDomain")
    @WebMethod(operationName = "SetWorkingDomain", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/SetWorkingDomain")
    @ResponseWrapper(localName = "SetWorkingDomainResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.SetWorkingDomainResponse")
    public void setWorkingDomain(
        @WebParam(name = "domainId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String domainId
    );

    @RequestWrapper(localName = "Login", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.Login")
    @WebMethod(operationName = "Login", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.LoginResponse")
    public void login(
        @WebParam(name = "credentials", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        com.mulesoft.demo.sumtotal.client.auth.UserCredentials credentials
    );

    @WebResult(name = "GetWorkingDomainResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
    @RequestWrapper(localName = "GetWorkingDomain", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.GetWorkingDomain")
    @WebMethod(operationName = "GetWorkingDomain", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/GetWorkingDomain")
    @ResponseWrapper(localName = "GetWorkingDomainResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.GetWorkingDomainResponse")
    public java.lang.String getWorkingDomain();

    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.ChangePassword")
    @WebMethod(operationName = "ChangePassword", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "oldPassword", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String oldPassword,
        @WebParam(name = "newPassword", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String newPassword
    );

    @RequestWrapper(localName = "Logout", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.Logout")
    @WebMethod(operationName = "Logout", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", className = "com.mulesoft.demo.sumtotal.client.auth.LogoutResponse")
    public void logout();
}
