package com.mulesoft.demo.sumtotal.client.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-20T11:38:58.523-07:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", name = "AuthenticationHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AuthenticationHttpPost {

    @WebResult(name = "string", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/", partName = "Body")
    @WebMethod(operationName = "GetWorkingDomain")
    public java.lang.String getWorkingDomain();

    @WebResult(name = "User", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/", partName = "Body")
    @WebMethod(operationName = "GetLoggedInUser")
    public User getLoggedInUser(
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String populationLevel
    );

    @WebMethod(operationName = "ChangePassword")
    public void changePassword(
        @WebParam(partName = "oldPassword", name = "oldPassword", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String oldPassword,
        @WebParam(partName = "newPassword", name = "newPassword", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String newPassword
    );

    @WebMethod(operationName = "SetWorkingDomain")
    public void setWorkingDomain(
        @WebParam(partName = "domainId", name = "domainId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/Authentication/")
        java.lang.String domainId
    );

    @WebMethod(operationName = "Logout")
    public void logout();
}
