/**
 * This file was automatically generated by the Mule Development Kit
 */
package com.mulesoft.demo.sumtotal;

import com.sumtotalsystems.sumtotal7.sumtotalbo.User;
import com.sumtotalsystems.sumtotal7.sumtotalws.UserToken;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.param.Optional;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name="sumtotal", schemaVersion="1.0-SNAPSHOT")
public class SumTotalConnector {
    private static UserToken USER_TOKEN = new UserToken();

    /**
     * Connect
     *
     * @param username A username
     * @param password A password
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey String username, String password) throws ConnectionException {
        USER_TOKEN = SumTotalClient.doAuth(username, password);
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        SumTotalClient.endSession(USER_TOKEN);
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        return USER_TOKEN.getValue() != null;
    }

    /**
     * Are we connected
     */
    @ConnectionIdentifier
    public String connectionId() {
        return USER_TOKEN.getValue();
    }

    /**
     * FOR DEBUG ONLY
     *
     * {@sample.xml ../../../doc/SumTotal-connector.xml.sample sumtotal:my-processor}
     *
     * @param content Content to be processed
     * @return Some string
     */
    /*@Processor
    public String getSecurityToken(String content) {
        return "USER TOKEN IS " + USER_TOKEN.getValue();
    }*/

    /**
     * Create User
     *
     * {@sample.xml ../../../doc/SumTotal-connector.xml.sample sumtotal:my-processor}
     *
     * @param @Optional Content to be processed
     * @return Some string
     */
    @Processor
    public User createUser(String userName, String firstName, String lastName, String email, String domainID,
                           String securityRoleID, String languageID, String timezoneID) {
        return SumTotalClient.doCreateUser(userName, firstName, lastName, email, domainID, securityRoleID, languageID, timezoneID, USER_TOKEN);
    }

    /**
     * Custom processor
     *
     * {@sample.xml ../../../doc/SumTotal-connector.xml.sample sumtotal:my-processor}
     *
     * @param content Content to be processed
     * @return Some string
     */
    @Processor
    public String findUser(String userName) {
        return "NOT IMPLEMENTED YET";
    }
}
