package com.mulesoft.demo.sumtotal.client.users;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-20T11:08:11.030-07:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", name = "UserManagementHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserManagementHttpPost {

    @WebMethod(operationName = "AddUpdateRequiredSkill")
    public void addUpdateRequiredSkill(
        @WebParam(partName = "toUsrId", name = "toUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String toUsrId,
        @WebParam(partName = "requiredSkillId", name = "requiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String requiredSkillId,
        @WebParam(partName = "prtyId", name = "prtyId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String prtyId,
        @WebParam(partName = "profValueId", name = "profValueId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String profValueId,
        @WebParam(partName = "notes", name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String notes
    );

    @WebMethod(operationName = "RemoveRequiredActivity")
    public void removeRequiredActivity(
        @WebParam(partName = "removedUserRequiredActivityId", name = "removedUserRequiredActivityId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String removedUserRequiredActivityId
    );

    @WebResult(name = "ArrayOfUserRequiredSkill", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetRequiredSkills")
    public ArrayOfUserRequiredSkill2 getRequiredSkills(
        @WebParam(partName = "forUsrId", name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String forUsrId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebMethod(operationName = "RemoveAcquiredSkill")
    public void removeAcquiredSkill(
        @WebParam(partName = "removeAcquiredSkillId", name = "removeAcquiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String removeAcquiredSkillId
    );

    @WebResult(name = "boolean", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "IsCertification")
    public boolean isCertification(
        @WebParam(partName = "inUserId", name = "inUserId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String inUserId,
        @WebParam(partName = "inCertId", name = "inCertId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String inCertId
    );

    @WebResult(name = "string", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "RefreshAudience")
    public java.lang.String refreshAudience(
        @WebParam(partName = "audID", name = "audID", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String audID
    );

    @WebResult(name = "ArrayOfUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetUsers")
    public ArrayOfUser getUsers(
        @WebParam(partName = "inDomainId", name = "inDomainId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String inDomainId,
        @WebParam(partName = "searchFilter", name = "searchFilter", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String searchFilter,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebMethod(operationName = "AddUpdateRequiredCompetency")
    public void addUpdateRequiredCompetency(
        @WebParam(partName = "toUsrId", name = "toUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String toUsrId,
        @WebParam(partName = "requiredCompId", name = "requiredCompId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String requiredCompId,
        @WebParam(partName = "prtyId", name = "prtyId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String prtyId,
        @WebParam(partName = "notes", name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String notes
    );

    @WebResult(name = "ArrayOfUserRequiredCompetency", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetRequiredCompetencies")
    public ArrayOfUserRequiredCompetency2 getRequiredCompetencies(
        @WebParam(partName = "forUsrId", name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String forUsrId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebResult(name = "User", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/", partName = "Body")
    @WebMethod(operationName = "GetUserById")
    public User getUserById(
        @WebParam(partName = "usrId", name = "usrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String usrId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebMethod(operationName = "AddUpdateAcquiredSkill")
    public void addUpdateAcquiredSkill(
        @WebParam(partName = "toUsrId", name = "toUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String toUsrId,
        @WebParam(partName = "acquiredSkillId", name = "acquiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String acquiredSkillId,
        @WebParam(partName = "profValueId", name = "profValueId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String profValueId,
        @WebParam(partName = "acqFirstDt", name = "acqFirstDt", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String acqFirstDt,
        @WebParam(partName = "acqLastDt", name = "acqLastDt", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String acqLastDt,
        @WebParam(partName = "notes", name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String notes
    );

    @WebResult(name = "ArrayOfEvaluation", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetPendingEvaluations")
    public ArrayOfEvaluation getPendingEvaluations(
        @WebParam(partName = "forUsrId", name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String forUsrId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebResult(name = "ArrayOfUserAcquiredSkill", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetAcquiredSkills")
    public ArrayOfUserAcquiredSkill2 getAcquiredSkills(
        @WebParam(partName = "forUsrId", name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String forUsrId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebResult(name = "ArrayOfDomainUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetMemberDomains")
    public ArrayOfDomainUser2 getMemberDomains(
        @WebParam(partName = "forUsrId", name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String forUsrId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebResult(name = "User", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/", partName = "Body")
    @WebMethod(operationName = "CreateEmptyUser")
    public User createEmptyUser();

    @WebResult(name = "User", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/", partName = "Body")
    @WebMethod(operationName = "GetUserByUserName")
    public User getUserByUserName(
        @WebParam(partName = "inDomainId", name = "inDomainId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String inDomainId,
        @WebParam(partName = "usrName", name = "usrName", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String usrName,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebMethod(operationName = "AddUpdateRequiredActivity")
    public void addUpdateRequiredActivity(
        @WebParam(partName = "toUserId", name = "toUserId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String toUserId,
        @WebParam(partName = "requiredActivityId", name = "requiredActivityId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String requiredActivityId,
        @WebParam(partName = "prtyId", name = "prtyId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String prtyId,
        @WebParam(partName = "grdId", name = "grdId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String grdId,
        @WebParam(partName = "notes", name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String notes
    );

    @WebMethod(operationName = "UserAudienceRefresh")
    public void userAudienceRefresh(
        @WebParam(partName = "EmpID", name = "EmpID", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String empID
    );

    @WebResult(name = "ArrayOfUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "SearchUsersByPath")
    public ArrayOfUser searchUsersByPath(
        @WebParam(partName = "path", name = "path", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String path,
        @WebParam(partName = "returnProperties", name = "returnProperties", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String returnProperties
    );

    @WebResult(name = "ArrayOfUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetTRUsers")
    public ArrayOfUser getTRUsers(
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebResult(name = "ArrayOfUserRequiredActivity", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", partName = "Body")
    @WebMethod(operationName = "GetRequiredActivities")
    public ArrayOfUserRequiredActivity2 getRequiredActivities(
        @WebParam(partName = "forUserId", name = "forUserId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String forUserId,
        @WebParam(partName = "populationLevel", name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String populationLevel
    );

    @WebMethod(operationName = "RemoveRequiredSkill")
    public void removeRequiredSkill(
        @WebParam(partName = "removedUserRequiredSkillId", name = "removedUserRequiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String removedUserRequiredSkillId
    );

    @WebMethod(operationName = "RemoveRequiredCompetency")
    public void removeRequiredCompetency(
        @WebParam(partName = "removedUserRequiredCompId", name = "removedUserRequiredCompId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String removedUserRequiredCompId
    );

    @WebResult(name = "User", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/", partName = "Body")
    @WebMethod(operationName = "DeleteUser")
    public User deleteUser(
        @WebParam(partName = "usrId", name = "usrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        java.lang.String usrId
    );
}
