
package com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.sumtotalsystems.sumtotal7.sumtotalbo.User;
import com.sumtotalsystems.sumtotal7.sumtotalws.UserSecurityContext;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserManagementSoap", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
@XmlSeeAlso({
    com.sumtotalsystems.sumtotal7.sumtotalbo.ObjectFactory.class,
    com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ObjectFactory.class,
    com.sumtotalsystems.sumtotal7.sumtotalws.ObjectFactory.class
})
public interface UserManagementSoap {


    /**
     * 
     * @param usrId
     * @param userSecurityContext
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "GetUserById", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetUserById")
    @WebResult(name = "GetUserByIdResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "GetUserById", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetUserById")
    @ResponseWrapper(localName = "GetUserByIdResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetUserByIdResponse")
    public User getUserById(
        @WebParam(name = "usrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String usrId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param inDomainId
     * @param userSecurityContext
     * @param searchFilter
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUser
     */
    @WebMethod(operationName = "GetUsers", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetUsers")
    @WebResult(name = "GetUsersResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetUsers", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetUsers")
    @ResponseWrapper(localName = "GetUsersResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetUsersResponse")
    public ArrayOfUser getUsers(
        @WebParam(name = "inDomainId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String inDomainId,
        @WebParam(name = "searchFilter", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String searchFilter,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "CreateEmptyUser", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/CreateEmptyUser")
    @WebResult(name = "CreateEmptyUserResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "CreateEmptyUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.CreateEmptyUser")
    @ResponseWrapper(localName = "CreateEmptyUserResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.CreateEmptyUserResponse")
    public User createEmptyUser(
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param usr
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "CreateUser", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/CreateUser")
    @WebResult(name = "CreateUserResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.CreateUserResponse")
    public User createUser(
        @WebParam(name = "usr", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
        User usr,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param usr
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "UpdateUser", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/UpdateUser")
    @WebResult(name = "UpdateUserResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.UpdateUserResponse")
    public User updateUser(
        @WebParam(name = "usr", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
        User usr,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param usrId
     * @param userSecurityContext
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "DeleteUser", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/DeleteUser")
    @WebResult(name = "DeleteUserResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.DeleteUserResponse")
    public User deleteUser(
        @WebParam(name = "usrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String usrId,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param prtyId
     * @param userSecurityContext
     * @param notes
     * @param profValueId
     * @param requiredSkillId
     * @param toUsrId
     */
    @WebMethod(operationName = "AddUpdateRequiredSkill", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/AddUpdateRequiredSkill")
    @RequestWrapper(localName = "AddUpdateRequiredSkill", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateRequiredSkill")
    @ResponseWrapper(localName = "AddUpdateRequiredSkillResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateRequiredSkillResponse")
    public void addUpdateRequiredSkill(
        @WebParam(name = "toUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String toUsrId,
        @WebParam(name = "requiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String requiredSkillId,
        @WebParam(name = "prtyId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String prtyId,
        @WebParam(name = "profValueId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String profValueId,
        @WebParam(name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String notes,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param removedUserRequiredSkillId
     * @param userSecurityContext
     */
    @WebMethod(operationName = "RemoveRequiredSkill", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/RemoveRequiredSkill")
    @RequestWrapper(localName = "RemoveRequiredSkill", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveRequiredSkill")
    @ResponseWrapper(localName = "RemoveRequiredSkillResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveRequiredSkillResponse")
    public void removeRequiredSkill(
        @WebParam(name = "removedUserRequiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String removedUserRequiredSkillId,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param forUsrId
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUserRequiredSkill
     */
    @WebMethod(operationName = "GetRequiredSkills", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetRequiredSkills")
    @WebResult(name = "GetRequiredSkillsResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetRequiredSkills", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetRequiredSkills")
    @ResponseWrapper(localName = "GetRequiredSkillsResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetRequiredSkillsResponse")
    public ArrayOfUserRequiredSkill getRequiredSkills(
        @WebParam(name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String forUsrId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param acqLastDt
     * @param acquiredSkillId
     * @param notes
     * @param profValueId
     * @param acqFirstDt
     * @param toUsrId
     */
    @WebMethod(operationName = "AddUpdateAcquiredSkill", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/AddUpdateAcquiredSkill")
    @RequestWrapper(localName = "AddUpdateAcquiredSkill", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateAcquiredSkill")
    @ResponseWrapper(localName = "AddUpdateAcquiredSkillResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateAcquiredSkillResponse")
    public void addUpdateAcquiredSkill(
        @WebParam(name = "toUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String toUsrId,
        @WebParam(name = "acquiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String acquiredSkillId,
        @WebParam(name = "profValueId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String profValueId,
        @WebParam(name = "acqFirstDt", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        XMLGregorianCalendar acqFirstDt,
        @WebParam(name = "acqLastDt", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        XMLGregorianCalendar acqLastDt,
        @WebParam(name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String notes,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param removeAcquiredSkillId
     */
    @WebMethod(operationName = "RemoveAcquiredSkill", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/RemoveAcquiredSkill")
    @RequestWrapper(localName = "RemoveAcquiredSkill", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveAcquiredSkill")
    @ResponseWrapper(localName = "RemoveAcquiredSkillResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveAcquiredSkillResponse")
    public void removeAcquiredSkill(
        @WebParam(name = "removeAcquiredSkillId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String removeAcquiredSkillId,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param forUsrId
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUserAcquiredSkill
     */
    @WebMethod(operationName = "GetAcquiredSkills", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetAcquiredSkills")
    @WebResult(name = "GetAcquiredSkillsResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetAcquiredSkills", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetAcquiredSkills")
    @ResponseWrapper(localName = "GetAcquiredSkillsResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetAcquiredSkillsResponse")
    public ArrayOfUserAcquiredSkill getAcquiredSkills(
        @WebParam(name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String forUsrId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param prtyId
     * @param userSecurityContext
     * @param requiredCompId
     * @param notes
     * @param toUsrId
     */
    @WebMethod(operationName = "AddUpdateRequiredCompetency", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/AddUpdateRequiredCompetency")
    @RequestWrapper(localName = "AddUpdateRequiredCompetency", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateRequiredCompetency")
    @ResponseWrapper(localName = "AddUpdateRequiredCompetencyResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateRequiredCompetencyResponse")
    public void addUpdateRequiredCompetency(
        @WebParam(name = "toUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String toUsrId,
        @WebParam(name = "requiredCompId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String requiredCompId,
        @WebParam(name = "prtyId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String prtyId,
        @WebParam(name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String notes,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param removedUserRequiredCompId
     * @param userSecurityContext
     */
    @WebMethod(operationName = "RemoveRequiredCompetency", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/RemoveRequiredCompetency")
    @RequestWrapper(localName = "RemoveRequiredCompetency", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveRequiredCompetency")
    @ResponseWrapper(localName = "RemoveRequiredCompetencyResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveRequiredCompetencyResponse")
    public void removeRequiredCompetency(
        @WebParam(name = "removedUserRequiredCompId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String removedUserRequiredCompId,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param forUsrId
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUserRequiredCompetency
     */
    @WebMethod(operationName = "GetRequiredCompetencies", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetRequiredCompetencies")
    @WebResult(name = "GetRequiredCompetenciesResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetRequiredCompetencies", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetRequiredCompetencies")
    @ResponseWrapper(localName = "GetRequiredCompetenciesResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetRequiredCompetenciesResponse")
    public ArrayOfUserRequiredCompetency getRequiredCompetencies(
        @WebParam(name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String forUsrId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param prtyId
     * @param toUserId
     * @param userSecurityContext
     * @param notes
     * @param grdId
     * @param requiredActivityId
     */
    @WebMethod(operationName = "AddUpdateRequiredActivity", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/AddUpdateRequiredActivity")
    @RequestWrapper(localName = "AddUpdateRequiredActivity", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateRequiredActivity")
    @ResponseWrapper(localName = "AddUpdateRequiredActivityResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.AddUpdateRequiredActivityResponse")
    public void addUpdateRequiredActivity(
        @WebParam(name = "toUserId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String toUserId,
        @WebParam(name = "requiredActivityId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String requiredActivityId,
        @WebParam(name = "prtyId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String prtyId,
        @WebParam(name = "grdId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String grdId,
        @WebParam(name = "notes", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String notes,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param removedUserRequiredActivityId
     */
    @WebMethod(operationName = "RemoveRequiredActivity", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/RemoveRequiredActivity")
    @RequestWrapper(localName = "RemoveRequiredActivity", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveRequiredActivity")
    @ResponseWrapper(localName = "RemoveRequiredActivityResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RemoveRequiredActivityResponse")
    public void removeRequiredActivity(
        @WebParam(name = "removedUserRequiredActivityId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String removedUserRequiredActivityId,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param forUserId
     * @param userSecurityContext
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUserRequiredActivity
     */
    @WebMethod(operationName = "GetRequiredActivities", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetRequiredActivities")
    @WebResult(name = "GetRequiredActivitiesResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetRequiredActivities", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetRequiredActivities")
    @ResponseWrapper(localName = "GetRequiredActivitiesResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetRequiredActivitiesResponse")
    public ArrayOfUserRequiredActivity getRequiredActivities(
        @WebParam(name = "forUserId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String forUserId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param forUsrId
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfEvaluation
     */
    @WebMethod(operationName = "GetPendingEvaluations", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetPendingEvaluations")
    @WebResult(name = "GetPendingEvaluationsResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetPendingEvaluations", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetPendingEvaluations")
    @ResponseWrapper(localName = "GetPendingEvaluationsResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetPendingEvaluationsResponse")
    public ArrayOfEvaluation getPendingEvaluations(
        @WebParam(name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String forUsrId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param forUsrId
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfDomainUser
     */
    @WebMethod(operationName = "GetMemberDomains", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetMemberDomains")
    @WebResult(name = "GetMemberDomainsResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetMemberDomains", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetMemberDomains")
    @ResponseWrapper(localName = "GetMemberDomainsResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetMemberDomainsResponse")
    public ArrayOfDomainUser getMemberDomains(
        @WebParam(name = "forUsrId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String forUsrId,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param path
     * @param returnProperties
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUser
     */
    @WebMethod(operationName = "SearchUsersByPath", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/SearchUsersByPath")
    @WebResult(name = "SearchUsersByPathResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "SearchUsersByPath", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.SearchUsersByPath")
    @ResponseWrapper(localName = "SearchUsersByPathResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.SearchUsersByPathResponse")
    public ArrayOfUser searchUsersByPath(
        @WebParam(name = "path", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String path,
        @WebParam(name = "returnProperties", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String returnProperties,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param audID
     * @param userSecurityContext
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RefreshAudience", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/RefreshAudience")
    @WebResult(name = "RefreshAudienceResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "RefreshAudience", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RefreshAudience")
    @ResponseWrapper(localName = "RefreshAudienceResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.RefreshAudienceResponse")
    public String refreshAudience(
        @WebParam(name = "audID", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String audID,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param inCertId
     * @param userSecurityContext
     * @param inUserId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsCertification", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/IsCertification")
    @WebResult(name = "IsCertificationResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "IsCertification", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.IsCertification")
    @ResponseWrapper(localName = "IsCertificationResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.IsCertificationResponse")
    public boolean isCertification(
        @WebParam(name = "inUserId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String inUserId,
        @WebParam(name = "inCertId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String inCertId,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param empID
     */
    @WebMethod(operationName = "UserAudienceRefresh", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/UserAudienceRefresh")
    @RequestWrapper(localName = "UserAudienceRefresh", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.UserAudienceRefresh")
    @ResponseWrapper(localName = "UserAudienceRefreshResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.UserAudienceRefreshResponse")
    public void userAudienceRefresh(
        @WebParam(name = "EmpID", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String empID,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param orgs
     * @param jobs
     * @param userSecurityContext
     * @param isNew
     * @param usr
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "CreateUserAndUpdateJobOrg", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/CreateUserAndUpdateJobOrg")
    @WebResult(name = "CreateUserAndUpdateJobOrgResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "CreateUserAndUpdateJobOrg", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.CreateUserAndUpdateJobOrg")
    @ResponseWrapper(localName = "CreateUserAndUpdateJobOrgResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.CreateUserAndUpdateJobOrgResponse")
    public User createUserAndUpdateJobOrg(
        @WebParam(name = "usr", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
        User usr,
        @WebParam(name = "isNew", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        boolean isNew,
        @WebParam(name = "jobs", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        ArrayOfString jobs,
        @WebParam(name = "orgs", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        ArrayOfString orgs,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param userSecurityContext
     * @param populationLevel
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.ArrayOfUser
     */
    @WebMethod(operationName = "GetTRUsers", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetTRUsers")
    @WebResult(name = "GetTRUsersResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
    @RequestWrapper(localName = "GetTRUsers", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetTRUsers")
    @ResponseWrapper(localName = "GetTRUsersResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetTRUsersResponse")
    public ArrayOfUser getTRUsers(
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

    /**
     * 
     * @param inDomainId
     * @param userSecurityContext
     * @param populationLevel
     * @param usrName
     * @return
     *     returns com.sumtotalsystems.sumtotal7.sumtotalbo.User
     */
    @WebMethod(operationName = "GetUserByUserName", action = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/GetUserByUserName")
    @WebResult(name = "GetUserByUserNameResult", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalbo/")
    @RequestWrapper(localName = "GetUserByUserName", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetUserByUserName")
    @ResponseWrapper(localName = "GetUserByUserNameResponse", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", className = "com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.GetUserByUserNameResponse")
    public User getUserByUserName(
        @WebParam(name = "inDomainId", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String inDomainId,
        @WebParam(name = "usrName", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        String usrName,
        @WebParam(name = "populationLevel", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/")
        int populationLevel,
        @WebParam(name = "UserSecurityContext", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/", header = true, partName = "UserSecurityContext")
        UserSecurityContext userSecurityContext);

}
