
package com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserManagement", targetNamespace = "http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", wsdlLocation = "http://mtn-sademo-128.sumtotalsystems.com/SumTotalWS/Services/usermanagement.asmx?wsdl")
public class UserManagement
    extends Service
{

    private final static URL USERMANAGEMENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.UserManagement.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sumtotalsystems.sumtotal7.sumtotalws.usermanagement.UserManagement.class.getResource(".");
            url = new URL(baseUrl, "http://mtn-sademo-128.sumtotalsystems.com/SumTotalWS/Services/usermanagement.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mtn-sademo-128.sumtotalsystems.com/SumTotalWS/Services/usermanagement.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERMANAGEMENT_WSDL_LOCATION = url;
    }

    public UserManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagement() {
        super(USERMANAGEMENT_WSDL_LOCATION, new QName("http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", "UserManagement"));
    }

    /**
     * 
     * @return
     *     returns UserManagementSoap
     */
    @WebEndpoint(name = "UserManagementSoap")
    public UserManagementSoap getUserManagementSoap() {
        return super.getPort(new QName("http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", "UserManagementSoap"), UserManagementSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagementSoap
     */
    @WebEndpoint(name = "UserManagementSoap")
    public UserManagementSoap getUserManagementSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sumtotalsystems.com/sumtotal7/sumtotalws/UserManagement/", "UserManagementSoap"), UserManagementSoap.class, features);
    }

}
